### ISSUE TITLE
报错了,无法使用.

### ISSUE THREAD

**Issue by hxz393** [declan-haojin/hexo-auto-tag#4]
错误信息如下:
TypeError: Cannot read properties of undefined (reading 'enable')
    at Hexo.logic (D:\Software\开发\x2b.net\x2b.net-source\node_modules\hexo-auto-tag\lib\logic.js:46:31)
    at Hexo.tryCatcher (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\method.js:15:34)
    at D:\Software\开发\x2b.net\x2b.net-source\node_modules\hexo\lib\extend\filter.js:67:52
    at tryCatcher (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Software\开发\x2b.net\x2b.net-source\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by hxz393** [comment]
配置如下:
auto_tag:
  enable: true
  apiKey: 免费用户免费获取api key,额度5美元
  threshold: 0.23 # range: 0-1, 0.23 has been tested to be a good value. Lower values tend to result in fewer tags being assigned to a post.
  tags:
    - tag1
    - tag2
    - tag3

**Comment by declan-haojin** [comment]
配置项有缩进吗
```
auto_tag:
  enable: true
  apiKey: 免费用户免费获取api key,额度5美元
  threshold: 0.23 # range: 0-1, 0.23 has been tested to be a good value. Lower values tend to result in fewer tags being assigned to a post.
  tags:
  - tag1
  - tag2
  - tag3
```

**Comment by hxz393** [comment]
> 配置项有缩进吗
> 
> ```
> auto_tag:
>   enable: true
>   apiKey: 免费用户免费获取api key,额度5美元
>   threshold: 0.23 # range: 0-1, 0.23 has been tested to be a good value. Lower values tend to result in fewer tags being assigned to a post.
>   tags:
>   - tag1
>   - tag2
>   - tag3
> ```

对不起,是我没注意到格式问题.
现在已经不报错了,openai那边能收到请求,只是文章tag没有自动生成.暂时先不折腾了.
